
name: test
on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['^1.16', '^1.17', '^1.18', '^1.19']
    name: Test on Go ${{ matrix.go }}
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}
    - name: Declare some variables
      id: vars
      run: |
        echo "::set-output name=coverage_txt::${RUNNER_TEMP}/coverage.txt"
    - name: Test Coverage (pkg)
      run: go test ./... -race -coverprofile=${{ steps.vars.outputs.coverage_txt }}
    - name: Upload coverage
      if: ${{ matrix.go == '^1.19' }}
      uses: codecov/codecov-action@v2
      with:
        files: ${{ steps.vars.outputs.coverage_txt }}
